lang-file: spanish.yml
signs:
    first-line-text: "ctw"
    first-line-text-replacement: "&1LIBELULA&4CTW"
    on-invalid-room-replacement: "&4INVALID ROOM"
    on-invalid-map-replacement: "&4INVALID MAP"
    on-disabled-map: "&4DISABLED"
implement-spawn-cmd: true